/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-08-12 13:35:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;

public final class autorities_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


   
 public boolean isallowed(String requestedpage,String[] thepagesallowed,int[] theflag)
 {
  for(int k =0;k< thepagesallowed.length ; k++)
  {
    
    if(requestedpage.equalsIgnoreCase(thepagesallowed[k]))
    {
      if(theflag[k] == 1){return true;}
    } 
  }
  
  return false;
 }
 
 

 public boolean ispageallowed(String[] thepage,String[] theright,String pagerequired)
 {

  for(int k=0;k<thepage.length;k++)
  {
    if(thepage[k].equalsIgnoreCase(pagerequired))
    {
     if(theright[k].equalsIgnoreCase("1")){return true;}  
    }
  }

  return false;
 } 
 
 
 
 
public String getuid(String the_uname,Connection thecon)throws Exception
{

 int thisid= 0;
 ResultSet thers;
 
 thers = thecon.createStatement().executeQuery("select userid from fitservice.hawasudan_pgm_Users where username=N'"+ the_uname + "'");            
 while(thers.next()){thisid=thers.getInt(1);}thers.close();thers = null;
 
 return Integer.toString(thisid);
 
}
 
            

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String username;try{ username =  session.getAttribute("username").toString();}catch(Exception e){username=null;}
String password;try{password =  session.getAttribute("password").toString();}catch(Exception e){password=null;}
if(username==null || password==null) //user not logged in
{
session.invalidate();
response.sendRedirect("login.jsp");
}
else
{


  /////get user authorities/////////////
  Connection con=null;
  InitialContext ic = new InitialContext();
  DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/TheDB");
  con  = ds.getConnection();
  ResultSet rs = null;
  int userid= 0;

  try
  {
   rs = con.createStatement().executeQuery("SELECT userID from fitservice.hawasudan_pgm_Users where username=N'" + username.replaceAll("'", "''") + "' and password=N'" + password.replaceAll("'", "''") + "'");             
   userid = 0;
   while(rs.next()){userid = rs.getInt(1);}
   rs.close();rs = null;
  }catch(Exception e){}
  
  



  int reccount1 = 0 ;
  rs = null;
  try
  {
   rs = con.createStatement().executeQuery("SELECT count(*) from fitservice.hawasudan_pgm_UsersAuthorities where userID=" + userid);             
   while(rs.next()){reccount1 = rs.getInt(1);} 
   rs.close();rs = null;
  }catch(Exception e){}
  
  
  String[] thepage = new String[reccount1];
  int[] allowed = new int[reccount1];
  
  rs = null;
  int z =0;
  try
  {
   rs = con.createStatement().executeQuery("SELECT page, allowed from fitservice.hawasudan_pgm_UsersAuthorities where userID=" + userid);             
   while(rs.next()){thepage[z]=rs.getString(1);allowed[z]=rs.getInt(2);z=z+1;}
   rs.close();rs = null;
  }catch(Exception e){}
    










  rs = null;
  String indate=""; 
  String intime="";
  try
  {
   rs = con.createStatement().executeQuery("SELECT  CONVERT(char(10), lastlogintime, 101), convert(varchar,lastlogintime, 8)  from fitservice.hawasudan_pgm_Users where userID=" + userid);             
   while(rs.next()){indate=rs.getString(1);intime=rs.getString(2);}
   rs.close();rs = null;
  }catch(Exception e){}







  
  boolean allowedaccess = false;
  for(int k =0;k< thepage.length ; k++)
  {
//   if(thepage[k].equalsIgnoreCase("filteration.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("send.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("nicknames.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("smsonair.jsp")){if(allowed[k] == 1){allowedaccess =true;}}         
//   if(thepage[k].equalsIgnoreCase("search.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("badwords.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("operatorsproviders.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("upperinfo.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("lowerinfo.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("instructions.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("smscount.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
//   if(thepage[k].equalsIgnoreCase("smsdistribution.jsp")){if(allowed[k] == 1){allowedaccess =true;}}
   if(thepage[k].equalsIgnoreCase("autorities.jsp")){if(allowed[k] == 1){allowedaccess =true;}}                           
  }
  
  


// out.println(allowedaccess);

if(allowedaccess ==false)
{
response.sendRedirect("login_logout.jsp");
return;
}

else
{















//user pressed modify
if( request.getParameter("subUpdate")!=null) 
{
String curr_uid="0";
String curr_uname= request.getParameter("uname");
curr_uid = getuid(curr_uname,con);


rs=null;
if( request.getParameter("filteration")!=null) {con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=1 where page='filteration.jsp' and userid="+ curr_uid );  }
else{con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=0 where page='filteration.jsp' and userid="+ curr_uid );  }

if( request.getParameter("search")!=null) {con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=1 where page='search.jsp' and userid="+ curr_uid );  }
else {con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=0 where page='search.jsp' and userid="+ curr_uid );  }


if( request.getParameter("autorities")!=null) {con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=1 where page='autorities.jsp' and userid="+ curr_uid );  }
else  {con.createStatement().execute("update fitservice.hawasudan_pgm_UsersAuthorities set allowed=0 where page='autorities.jsp' and userid="+ curr_uid );  }


//phone numbers
if( request.getParameter("phone")!=null) {con.createStatement().execute("update fitservice.hawasudan_pgm_Users set phone=1 where userid="+ curr_uid );  }
else  {con.createStatement().execute("update fitservice.hawasudan_pgm_Users set phone=0 where userid="+ curr_uid );  }




}










///user pressed add
if( request.getParameter("subAdd")!=null) 
{
    
   int userFnd = 0;
   rs = con.createStatement().executeQuery("SELECT  count(*) as thecnt from fitservice.hawasudan_pgm_Users where username=N'" + request.getParameter("uname").trim() +"'");             
   while(rs.next()){userFnd=rs.getInt(1);}rs.close();rs = null;
   


if(userFnd == 0)
{
 String the__query ="insert into  fitservice.hawasudan_pgm_Users( username, password, description) values(N'"+ request.getParameter("uname") + "',N'"+ request.getParameter("pword") +"',N'" + request.getParameter("oname") + "')";
 con.createStatement().execute(the__query);  
 rs=null;
 rs = con.createStatement().executeQuery("select max(userid) from fitservice.hawasudan_pgm_Users;");
 int theID = 0;  
 while(rs.next()){ theID = rs.getInt(1);}rs.close();rs = null;
 
// out.println(theID);
 
 if(theID != 0)
 {
  con.createStatement().execute("insert into  fitservice.hawasudan_pgm_UsersAuthorities(userid, page, allowed) values("+ theID  + ",'filteration.jsp',0)");

  con.createStatement().execute("insert into  fitservice.hawasudan_pgm_UsersAuthorities(userid, page, allowed) values("+ theID  + ",'search.jsp',0)"); 
    
  con.createStatement().execute("insert into  fitservice.hawasudan_pgm_UsersAuthorities(userid, page, allowed) values("+ theID  + ",'autorities.jsp',0)"); 

 
 }
} 
 


}



///user pressed delete
if( request.getParameter("subDelete")!=null) 
{
//oname
//uname
//pword

String curr_uid="0";
String curr_uname= request.getParameter("uname");
curr_uid = getuid(curr_uname,con);


con.createStatement().execute("delete from fitservice.hawasudan_pgm_Users where username =N'"+ request.getParameter("uname") + "'"); 
con.createStatement().execute("delete from fitservice.hawasudan_pgm_UsersAuthorities where userid='" + curr_uid + "'"); 

}






///user pressed update password
if( request.getParameter("subpasswordupdate")!=null) 
{
//oname
//uname
//pword
con.createStatement().execute("update fitservice.hawasudan_pgm_Users set password=N'" + request.getParameter("pword") + "' where username =N'"+ request.getParameter("uname") + "'"); 

}






///////////////THE fitservice.hawasudan_pgm_Users

/// -------------------
int the_pgm_Userscount = 0;
String[] theuserid = null;
String[] theusername = null;
String[] thepassword = null;
String[] thedescrption = null;
String[] phoneallowed = null;

rs = con.createStatement().executeQuery("SELECT count(*) from fitservice.hawasudan_pgm_Users");            
if(rs.next()){the_pgm_Userscount = rs.getInt(1);}rs.close(); rs = null;
rs = con.createStatement().executeQuery("SELECT     userID, username, password, description,phone FROM         fitservice.hawasudan_pgm_Users ORDER BY userID");

theuserid = new String[the_pgm_Userscount];
theusername = new String[the_pgm_Userscount];
thepassword = new String[the_pgm_Userscount];
thedescrption = new String[the_pgm_Userscount];
phoneallowed = new String[the_pgm_Userscount];
   
int theCounterrr1 = 0;
   while(rs.next())
    {
         theuserid[theCounterrr1] = rs.getString(1);
         theusername[theCounterrr1] = rs.getString(2);
         thepassword[theCounterrr1] = rs.getString(3);
         thedescrption[theCounterrr1] = rs.getString(4);
         phoneallowed[theCounterrr1] = rs.getString(5);         
         
        theCounterrr1 = theCounterrr1 + 1 ;
   }
   rs.close(); 
   rs = null;
/// ------------------




String filteusername = "";
if( request.getParameter("filteusername")!=null) 
{
  filteusername = request.getParameter("filteusername");
}
///-----------------------------------


             




















      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html dir='rtl'>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<STYLE type=text/css>BODY {MARGIN: 0px; FONT: 14pt arial, geneva, lucida, \"lucida grande\", arial, helvetica, sans-serif; COLOR: #000000 }</style>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("<title>الصلاحيات ... Hawa AlSudan</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<form action='MainPage.jsp' method='post'>\r\n");
      out.write("<input type='hidden' name='uid' value='41'>\r\n");
      out.write("<input type='hidden' name='cur_page' value=''>\r\n");
      out.write("<table border='1' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%' height='80'>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width='21%' align='center'><b><i><font color='#A36103' size='6'>الصلاحيات</font></i></b></td>\r\n");
      out.write("    <td width='35%' align='center'>\r\n");
      out.write("    <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%'>\r\n");
      out.write("      <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b> وقــت الدخول  ");
      out.print( intime );
      out.write(" </b></font></td></tr>\r\n");
      out.write("      <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b> &nbsp;</b></font></td></tr>\r\n");
      out.write("      <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b> تاريــخ الدخول  ");
      out.print( indate );
      out.write(" </b></font></td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width='19%' align='center'>\r\n");
      out.write("    \t<table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%'>\r\n");
      out.write("    \t\t<tr><td align='center'><input type='submit' name='subMain' value='القائمة الرئيسية' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td></tr>\r\n");
      out.write("\r\n");
      out.write("    \t\t</form>\r\n");
      out.write("\t\t\t<form action='autorities.jsp' method='post'>\r\n");
      out.write("\t\t\t<input type='hidden' name='uid' value='41'>\r\n");
      out.write("    \t\t<tr><td align='center'><input type='submit' name='subRefresh' value='اعادة تحميل' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td></tr>\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </td>\r\n");
      out.write("<td bgcolor='#ffffff' width='15%' align='center'><IMG src='logo.png'></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table><br>\r\n");
      out.write("\t\t<table border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='60%'>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td width='30%' height='170' align='center' valign='top'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<select name='filteusername' size='8' style='font-family:arial black; font-style:bold; font-size:16; color:#000 ;background:#DCDCDC;width:12em' onChange='javascript:this.form.submit();'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
for (int l =0  ; l < theuserid.length ; l ++)
{
  if (theusername[l].equalsIgnoreCase(filteusername)) 
  {
  

      out.write("\r\n");
      out.write("    \t        <option selected>");
      out.print( (new String(theusername[l].getBytes("Cp1252"),"Cp1256")) );
      out.write("</option>       \t        \r\n");

  }
  else
  {

      out.write("       \t        \r\n");
      out.write("    \t        <option >");
      out.print( (new String(theusername[l].getBytes("Cp1252"),"Cp1256")) );
      out.write("</option>\r\n");

  }    	        
}

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t    <td width='55%' height='200' rowspan='2'>\r\n");
      out.write("\t\t    <table border='1' bgcolor=#DCDCDC align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='90%'>\r\n");
      out.write("\r\n");


   String accountowner="";
   String accusername="";
   String accpassword="";
   String accphone="";   
   

   rs = null;
   rs = con.createStatement().executeQuery("SELECT    username, password, description,phone  FROM fitservice.hawasudan_pgm_Users  where username=N'"+filteusername+"' order by userID limit 1");  
   while(rs.next()){accusername=rs.getString(1);accpassword=rs.getString(2);accountowner=rs.getString(3);accphone=rs.getString(4);}rs.close();rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width='50%' align='center' height='30'><b>اسم صاحب الحساب</b></td>\r\n");
      out.write("<td width='50%' align='center' height='30'><input type='text' name='oname' value='");
      out.print((new String(accountowner.getBytes("Cp1252"),"Cp1256")));
      out.write("' style='width:14em' size='20'></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width='50%' align='center' height='30'><b>اسم المستخدم</b></td>\r\n");
      out.write("<td width='50%' align='center' height='30'><input type='text' name='uname' value='");
      out.print((new String(accusername.getBytes("Cp1252"),"Cp1256")));
      out.write("' style='width:14em' size='20'></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width='50%' align='center' height='30'><b>كلمة المرور</b></td>\r\n");
      out.write("<td width='50%' align='center' height='30'><input type='password' name='pword' value='");
      out.print((new String(accpassword.getBytes("Cp1252"),"Cp1256")));
      out.write("' style='width:14em' size='20'></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width='50%' align='center' height='30'><b>ارقام الهواتف</b></td>\r\n");
      out.write("\t\t        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
if(accphone.equalsIgnoreCase("1"))
{

      out.write("\r\n");
      out.write("             <td width='50%' align='center' height='30'>\r\n");
      out.write("             <input type='checkbox' name='phone' value='1' CHECKED>\r\n");
      out.write("             </td>\r\n");

}
else
{

      out.write("\r\n");
      out.write("             <td width='50%' align='center' height='30'>\r\n");
      out.write("             <input type='checkbox' name='phone' value='0'>\r\n");
      out.write("             </td>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t    <br>\r\n");
      out.write("\t\t    <table border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='60%' height='17'>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td width='33%' height='30'><input type='submit' name='subAdd' value='اضافة مستخدم' style='font-weight:bold ; width:8em ; height:3em'></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(accusername.equalsIgnoreCase("admin") )
{

      out.write("\t\t        \r\n");
      out.write("\t\t        <td width='33%' height='30'><input disabled type='submit' name='subUpdate' value='تعديل صلاحيات مستخدم' style='font-weight:bold ; width:12em ; height:3em'></td>\r\n");
      out.write("\t\t        <td width='34%' height='30'><input disabled type='submit' name='subDelete' value='حذف مستخدم' style='font-weight:bold ; width:8em ; height:3em'></td>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t\t        <td width='33%' height='30'><input type='submit' name='subUpdate' value='تعديل صلاحيات مستخدم' style='font-weight:bold ; width:12em ; height:3em'></td>\r\n");
      out.write("\t\t        <td width='34%' height='30'><input type='submit' name='subDelete' value='حذف مستخدم' style='font-weight:bold ; width:8em ; height:3em'></td>\r\n");
      out.write("\t\t        \r\n");

}

      out.write("\t\t        \r\n");
      out.write("\r\n");
      out.write("\t\t        <td width='34%' height='30'><input type='submit' name='subpasswordupdate' value='تعديل كلمة المرور' style='font-weight:bold ; width:10em ; height:3em'></td>\t\t        \t\t        \t\t        \r\n");
      out.write("\t\t        \t\t        \r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t    <br>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   int autoritiescount = 0;
   rs = con.createStatement().executeQuery("select count(*) from fitservice.hawasudan_pgm_UsersAuthorities where userid=(select userid from fitservice.hawasudan_pgm_Users where username=N'"+filteusername+"')");  
   while(rs.next()){autoritiescount = rs.getInt(1);}rs.close();rs=null;
   
   String[] thepages = new String[autoritiescount];
   String[] isallowed = new String[autoritiescount];
   
   int ttt =0;
   rs = con.createStatement().executeQuery("select page, allowed from fitservice.hawasudan_pgm_UsersAuthorities where userid=(select userid from fitservice.hawasudan_pgm_Users where username=N'"+filteusername+"')");  
   while(rs.next()){thepages[ttt]=rs.getString(1);isallowed[ttt]=rs.getString(2);ttt=ttt+1;}rs.close();rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='100%'>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width='3%'>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width='22%' valign='top'>\r\n");
      out.write("\t\t\t\t    <!-- ........................ SMS Table .................... -->\r\n");
      out.write("\t\t\t\t    <table border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='100%'>\r\n");
      out.write("\t\t\t\t      <tr bgcolor=#646464><td width='100%' colspan='2' align='center' height='30'><b><font size='5' color=white>الرسائل القصيره</font></b></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
if(ispageallowed(thepages,isallowed,"filteration.jsp") )
{

      out.write("\r\n");
      out.write("<tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='filteration' value='1' CHECKED>&nbsp;<b><font size='3'>مراقبه</font></b></td></tr>\r\n");

}
else
{

      out.write("\r\n");
      out.write("<tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='filteration' value='0' >&nbsp;<b><font size='3'>مراقبه</font></b></td></tr>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
if(ispageallowed(thepages,isallowed,"search.jsp") )
{

      out.write("\r\n");
      out.write("                      <tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='search' value='1' CHECKED>&nbsp;<b><font size='3'>&nbsp;ارشيف</font></b></td></tr>\r\n");

}
else
{

      out.write("\r\n");
      out.write("                      <tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='search' value='0' >&nbsp;<b><font size='3'>&nbsp;ارشيف</font></b></td></tr>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("\t\t\t\t    <!-- ........................ End SMS Table .................... -->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width='2%'>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width='22%' valign='top'>\r\n");
      out.write("\t\t\t\t    <!-- ........................ Entry Table .................... -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t    <!-- ........................ End Programs Table .................... -->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width='2%'>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width='22%' valign='top'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td width='2%'>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width='22%' valign='top'>\r\n");
      out.write("\t\t\t\t    <!-- ........................ Admin Table .................... -->\r\n");
      out.write("\t\t\t\t    <table border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='100%'>\r\n");
      out.write("\t\t\t\t      <tr bgcolor=#646464><td width='100%' colspan='2' align='center' height='30'><b><font size='5' color=white>الاداره</font></b></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
if(ispageallowed(thepages,isallowed,"autorities.jsp") )
{

      out.write("\r\n");
      out.write("                              <tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='autorities' value='1' CHECKED>&nbsp;<b><font size='3'>&nbsp;الصلاحيات</font></b></td></tr>\r\n");

}
else
{

      out.write("\r\n");
      out.write("                              <tr><td width='25%' height='30' bgcolor=#DCDCDC>&nbsp;<input type='checkbox' name='autorities' value='0' >&nbsp;<b><font size='3'>&nbsp;الصلاحيات</font></b></td></tr>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t\t\t    <!-- ........................ End Admin Table .................... -->\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width='3%'>&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

}
con.close();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
