/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-12 19:41:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;

public final class AdminMainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


String pgmid;try{ pgmid =  session.getAttribute("pgmid").toString();}catch(Exception e){pgmid=null;}
String username;try{ username =  session.getAttribute("username").toString();}catch(Exception e){username=null;}
String password;try{password =  session.getAttribute("password").toString();}catch(Exception e){password=null;}

if( pgmid.equalsIgnoreCase("admin")  ) //admin login
{


  

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html dir='rtl'>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<STYLE type=text/css>BODY {MARGIN: 0px; FONT: 14pt Arabic Transparent, geneva, lucida, \"lucida grande\", Arabic Transparent, helvetica, sans-serif; COLOR: #000000 }</style>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("<title>القائمة الرئيسية ... National Radio</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("<table border='0' bgcolor=#ffffff cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%' height='85'>\r\n");
      out.write("  <tr>\r\n");
      out.write("\t<td width='25%' align='center'><font size='5' Color=darkred><b>مرحباً ,</b></font><font size='4' Color=green><b> ");
      out.print( username );
      out.write(" </b></font></td>\r\n");
      out.write("    <td width='25%' align='center'>&nbsp;</td>\r\n");
      out.write("    <td width='25%' align='center'><font size='4' Color=black><a href=\"ftp://");
      out.print(username );
      out.write(':');
      out.print(password );
      out.write("@196.29.186.246\"><b>تصفح التسجيلات</b></a></font></td>\r\n");
      out.write("    <td bgcolor='#ffffff' width='25%' align='left'><IMG src='logo.png'></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <table border='0' alin='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='90%'>\r\n");
      out.write("                  <tr>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \t\r\n");
      out.write("      \t\r\n");
      out.write("      \t\r\n");
      out.write("      \t\r\n");
      out.write("      \r\n");
      out.write("                    <td width='25%' align='center' >\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <table align='center' border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='15%'>\r\n");
      out.write("                    \r\n");
      out.write("                        <tr bgcolor=#646464>\r\n");
      out.write("                              <td width='50%'  align='center' height='30'><b><font size='4' color=white>الاداره</font></b></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t     \t\t <tr bgcolor=#DCDCDC>\r\n");
      out.write("\t\t\t     \t\t \t<form action='programs.jsp' method='post'>\r\n");
      out.write("\t\t\t\t                <td width='50%' height='40'><p align='center'><input type='submit'  value='البرامج' STYLE='font-family:Arabic Transparent;font-weight:bold; font-size:12pt ; width:8em ; height:2.0em'></td>\r\n");
      out.write("\t\t\t\t\t\t   </form>\r\n");
      out.write("\t\t\t      \t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t     \t\t <tr bgcolor=#DCDCDC>\r\n");
      out.write("\t\t\t     \t\t \t<form action='search.jsp' method='post'>\r\n");
      out.write("\t\t\t\t                <td width='50%' height='40'><p align='center'><input type='submit'  value='البحث' STYLE='font-family:Arabic Transparent;font-weight:bold; font-size:12pt ; width:8em ; height:2.0em'></td>\r\n");
      out.write("\t\t\t\t\t\t   </form>\r\n");
      out.write("\t\t\t      \t\t</tr>\r\n");
      out.write("\t\t\t      \t\t\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\r\n");
      out.write("\t\t\t      \t\t\r\n");
      out.write("\t\t\t      \t\t\r\n");
      out.write("\t\t\t      \t\t\t      \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    \t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  \t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='95%'>\r\n");
      out.write("\t  \t\t\t\t<tr align='center'>\r\n");
      out.write("\r\n");
      out.write("\t    \t\t\t\t<td width='25%' valign='top'>&nbsp;</td>\r\n");
      out.write("\t    \t\t\t\t<td width='25%' valign='top'>&nbsp;</td>\r\n");
      out.write("\t    \t\t\t\t<td width='25%' valign='top'>&nbsp;</td>\r\n");
      out.write("\t    \t\t\t\t<td width='25%' valign='top'>\r\n");
      out.write("\t    \t\t\t\t\r\n");
      out.write("\t\t\t\t\t    \t<table border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='60%'>\r\n");
      out.write("\t\t\t\t\t\t      <tr bgcolor=#DCDCDC align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form action='login_logout.jsp' method='post'>\r\n");
      out.write("\t\t\t\t\t                  <td width='80%' height='40'><p align='center'><input type='submit' value='خروج' STYLE='font-family:Arabic Transparent;font-weight:bold; color:#FF0000; font-size:12pt ; width:8em ;  height:2.0em'></td>\r\n");
      out.write("\t\t\t\t\t\t\t    </form>\r\n");
      out.write("\t\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t    \t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t  \t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


}

else
{

	session.invalidate();
	response.sendRedirect("login.jsp");

}



    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
