/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-12 19:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;
import java.util.regex.*;

public final class programs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String username;try{ username =  session.getAttribute("username").toString();}catch(Exception e){username=null;}
String password;try{password =  session.getAttribute("password").toString();}catch(Exception e){password=null;}
if(username==null) //user not logged in
{
session.invalidate();
response.sendRedirect("login.jsp");
}

else
{


		   
  
  

  Connection con=null;
  InitialContext ic = new InitialContext();
  DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/TheDB");
  con  = ds.getConnection();
  ResultSet rs = null;



  String generalpass="";
  rs = con.createStatement().executeQuery("SELECT thepassword from sms.nradio_superusers where theuser='general'");             
  while(rs.next()){generalpass = rs.getString(1); }rs.close(); rs = null;

		   
  String adminpass="";
  rs = con.createStatement().executeQuery("SELECT thepassword from sms.nradio_superusers where theuser='admin'");             
  while(rs.next()){adminpass = rs.getString(1); }rs.close(); rs = null;







  rs = null;
  String indate=""; 
  String intime="";








 
 
 
 
 
 
  rs = null;







String pgmstatus= "0"; 
//try{pgmstatus = request.getParameter("pgmstatus").trim();}catch(Exception e){pgmstatus = "0";}
 rs = con.createStatement().executeQuery("SELECT status FROM sms.nradio_operations");            
 while(rs.next()){pgmstatus = rs.getString(1);}
 rs.close(); rs = null;


   
 

 int count=0;
 rs = con.createStatement().executeQuery("select count(*) from sms.nradio_pgms ");            
 while(rs.next()){count = rs.getInt(1);}
 rs.close(); rs = null;

   

   

             

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html dir='rtl'>\r\n");
      out.write("<HEAD>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script LANGUAGE=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function correctinvoke(target)\r\n");
      out.write("{\r\n");
      out.write("if(target == 0) {document.thisfrm.action=\"addprogram.jsp\";document.thisfrm.submit();}\r\n");
      out.write("\r\n");
      out.write("if(target == 1) {document.thisfrm.action=\"modifyprov.jsp\";document.thisfrm.submit();}\r\n");
      out.write("if(target == 2) {document.thisfrm.action=\"deleteprov.jsp\";document.thisfrm.submit();}\r\n");
      out.write("\r\n");
      out.write("if(target == 3) {document.accountingfrm.action=\"addprovaccountingfrm.jsp\";document.accountingfrm.submit();}\r\n");
      out.write("if(target == 4) {document.accountingfrm.action=\"modifyprovaccountingfrm.jsp\";document.accountingfrm.submit();}\r\n");
      out.write("if(target == 5) {document.accountingfrm.action=\"deleteprovaccountingfrm.jsp\";document.accountingfrm.submit();}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function viewarabicurl(theID,theapp)\r\n");
      out.write("{\r\n");
      out.write("var thecountry = document.getElementById('thecountry' + theID).value;\r\n");
      out.write("var thecoperator = document.getElementById('thecoperator' + theID).value;\r\n");
      out.write("var theprovidername = document.getElementById('theprovidername' + theID).value;\r\n");
      out.write("var theshortcode = document.getElementById('theshortcode' + theID).value;\r\n");
      out.write("prompt('\\u0645\\u062B\\u0627\\u0644\\u0020\\u0644\\u0631\\u0627\\u0628\\u0637\\u0020\\u0627\\u0644\\u0631\\u0633\\u0627\\u0626\\u0644\\u0020\\u0627\\u0644\\u0639\\u0631\\u0628\\u064A', theapp + '?provider=' + theprovidername + '&country=' + thecountry +'&operator='+ thecoperator + '&shortcode=' +theshortcode +'&msisdn=20121234567&lang=A&contents=062A062C0631064A0628');\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function viewURLEnglish(theID,theapp)\r\n");
      out.write("{\r\n");
      out.write("var thecountry = document.getElementById('thecountry' + theID).value;\r\n");
      out.write("var thecoperator = document.getElementById('thecoperator' + theID).value;\r\n");
      out.write("var theprovidername = document.getElementById('theprovidername' + theID).value;\r\n");
      out.write("var theshortcode = document.getElementById('theshortcode' + theID).value;\r\n");
      out.write("prompt('\\u0645\\u062B\\u0627\\u0644\\u0020\\u0644\\u0631\\u0627\\u0628\\u0637\\u0020\\u0627\\u0644\\u0631\\u0633\\u0627\\u0626\\u0644\\u0020\\u0627\\u0644\\u0627\\u0646\\u062C\\u0644\\u064A\\u0632\\u064A', theapp + '?provider=' + theprovidername + '&country=' + thecountry +'&operator='+ thecoperator + '&shortcode=' +theshortcode +'&msisdn=20121234567&lang=E&contents=test');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function thecorrectinvoke(whattocall)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("if(whattocall == 0) {document.thethisfrm.action=\"thebatchprogramsmodify.jsp\";document.thethisfrm.submit();}\r\n");
      out.write("if(whattocall == 1) \r\n");
      out.write("\t\t\t\t   {\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\tvar r = confirm(\"Are you sure you want to delete ?\");\r\n");
      out.write("\t\t\t\t\t\t\tif (r == true) \r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  document.thethisfrm.action=\"thebatchprogramsdelete.jsp\";document.thethisfrm.submit();\r\n");
      out.write("\t\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\t\telse \r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectall(k)\r\n");
      out.write("{\r\n");
      out.write("\tfor( i=0; i< k; i++ )\r\n");
      out.write("\t{ \r\n");
      out.write("\t if( document.getElementById('ischeck' + i) != null )  \r\n");
      out.write("     { \r\n");
      out.write("\t   document.getElementById('ischeck' + i).checked = true; \r\n");
      out.write("\t }\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function startTime() \r\n");
      out.write("{\r\n");
      out.write("    var today=new Date();\r\n");
      out.write(" \r\n");
      out.write(" \tvar x1=  today.getYear() + \"-\" + today.getMonth() + \"-\" + today.getDate() ; \r\n");
      out.write("    \r\n");
      out.write("    var h=today.getHours();\r\n");
      out.write("    var m=today.getMinutes();\r\n");
      out.write("    var s=today.getSeconds();\r\n");
      out.write("    m = checkTime(m);\r\n");
      out.write("    s = checkTime(s);\r\n");
      out.write("    document.getElementById('txt').innerHTML = x1+\" \"+ h+\":\"+m+\":\"+s;\r\n");
      out.write("    var t = setTimeout(function(){startTime()},500);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkTime(i) {\r\n");
      out.write("    if (i<10) {i = \"0\" + i};  // add zero in front of numbers < 10\r\n");
      out.write("    return i;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<STYLE type=text/css>BODY {MARGIN: 0px; FONT: 14pt arial, geneva, lucida, \"lucida grande\", arial, helvetica, sans-serif; COLOR: #000000;background-color: #FFFFFF; }</style>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("<title>National radio ... Programs%></title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<BODY onload=\"startTime()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String applicationAt = "http://" + request.getHeader("Host") +request.getContextPath() + "/" +"submit.jsp";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border='1' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%' height='80'>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width='21%' align='center'><b><i><font color='#A36103' size='6'>البرامج</font></i></b></td>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <td width='35%' align='center'>\r\n");
      out.write("\t\t    <table dir='ltr' border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='75%'>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t      \t\t<td colspan=3 width='25%' align='center'><font color='#000000' face='Arial' size='2'><b>Super Users</b></font></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t       <tr>\r\n");
      out.write("\t\t      \t\t<td  width='25%' align='center'><font color='#000000' face='Arial' size='2'>username</font></td>\r\n");
      out.write("\t\t      \t\t<td  width='25%' align='center'><font color='#000000' face='Arial' size='2'>password</font></td>\r\n");
      out.write("\t\t      \t\t<td  width='25%' align='center'><font color='#000000' face='Arial' size='2'>&nbsp;</font></td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      \t\t\t\t    \r\n");
      out.write("\t\t    <form action='changeadminpass.jsp' method='get'> \r\n");
      out.write("\t\t      <tr >\r\n");
      out.write("\t\t      \t\t<td width='25%' align='center'><font color='#000000' face='Arial' size='2'><b>admin</b></font></td>\r\n");
      out.write("                    <td width='50%' align='center'><INPUT type='text' dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:12em;height:1.5em' NAME=adminpass value='");
      out.print(adminpass);
      out.write("' ></td>\r\n");
      out.write("                    <td width='25%' align='center'><input type='submit' value='change password' STYLE='font-weight:bold ; width:10em ; height:2.0em'></td>\r\n");
      out.write("\t\t      \t\t\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t     </form> \r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t    <form action='changegeneralpass.jsp' method='get'> \r\n");
      out.write("\t\t      <tr >\r\n");
      out.write("\t\t      \t\t<td width='25%' align='center'><font color='#000000' face='Arial' size='2'><b>general</b></font></td>\r\n");
      out.write("                    <td width='50%' align='center'><INPUT type='text' dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:12em;height:1.5em' NAME=generalpass value='");
      out.print(generalpass);
      out.write("' ></td>\r\n");
      out.write("                    <td width='25%' align='center'><input type='submit' value='change password' STYLE='font-weight:bold ; width:10em ; height:2.0em'></td>\r\n");
      out.write("\t\t      \t\t\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t     </form> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("    </td>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <td width='19%' align='center'>\r\n");
      out.write("    \t<table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%'>\r\n");
      out.write(" \t\t<form action='AdminMainPage.jsp' method='post'>                \r\n");
      out.write("     \t\t <tr><td align='center'><input type='submit' name='subMain' value='القائمة الرئيسية' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td></tr>\r\n");
      out.write("                </form>\r\n");
      out.write(" \t\t<form name='theform' action='programs.jsp' method='post'>\r\n");
      out.write("     \t\t<tr><td align='center'><input type='submit' name='subRefresh' value='اعادة تحميل' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td></tr>\r\n");
      out.write("               </form>\r\n");
      out.write("    \t</table>\r\n");
      out.write("    </td>\r\n");
      out.write("<td bgcolor='#ffffff' width='15%' align='center'><IMG src='logo.png'></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <table align='center' border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='90%'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<td width='50%' align='center'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("      <table align='center' border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='75%'>\r\n");
      out.write("\r\n");
      out.write("   \t\t<form name=thisfrm  method=post action=\"\">\r\n");
      out.write(" \t    \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td colspan=2 align='center'><b>برنامج جديد</b></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t       \t    \r\n");
      out.write("\r\n");
      out.write("       \t    \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>اسم البرنامج</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:15em;height:1.5em' dir='rtl' name='pgmname' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t   \r\n");
      out.write("       \t    \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>يوم البث</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("                       <select name='pgmairingday'  style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em'  >\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t </select>\r\n");
      out.write("    \t        \t\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>بداية البث</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:7em;height:1.5em' dir='ltr' name='pgmairingstart' value='00:00:01' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t            \t      \r\n");
      out.write("      \t      \r\n");
      out.write("  \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>نهاية البث</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:7em;height:1.5em' dir='ltr' name='pgmairingend' value='00:01:00' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t            \t            \t      \r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>يوم الاعاده</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("                       <select name='pgmreplayday'  style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em'  >\r\n");
      out.write("                       \t\t\t<option  value='NOREPLAY'>لا اعاده</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t </select>\r\n");
      out.write("    \t        \t\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>بداية البث</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:7em;height:1.5em' dir='ltr' name='pgmreplaystart' value='13:00:01' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t            \t      \r\n");
      out.write("      \t      \r\n");
      out.write("  \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>نهاية البث</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:7em;height:1.5em' dir='ltr' name='pgmreplayend' value='13:01:00' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t            \t            \t      \r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>اسم المستخدم</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:10em;height:1.5em' dir='ltr' name='usrname' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td width='30%' align='center'><b>كلمة المرور</b></td>\r\n");
      out.write("      \t        <td width='70%' align='right'>\r\n");
      out.write("      \t        \t<INPUT type='text' style='font-size:12pt;color:#000000;font-weight:bold;width:10em;height:1.5em' dir='ltr' name='password' >\r\n");
      out.write("      \t       \t</td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t      \r\n");
      out.write("      \t      \r\n");
      out.write("      \t       <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("      \t        <td colspan=2  align='center'><input type='button' name='subAdd' value='اضافة' style='font-weight:bold ; width:9em ; height:2.5em' onClick=\"correctinvoke(0)\"></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t    </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<td width='75%' align='center'>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("            <table border='1' bgcolor=#FFFFFF align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='75%' >\r\n");
      out.write("\t     <form action='pgmstatus.jsp' method='post'> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(pgmstatus.equalsIgnoreCase("0"))
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <tr bgcolor=#AA7777 >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
                                    else
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <tr bgcolor=#7777AA >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t     \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("                <td colspan=2 height='40' align='center'><b><font color='FFFFFF' size='3'>توجيه الرسائل</font></b></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("              <tr> \r\n");
      out.write("                \r\n");
      out.write("                <td width='50%' align='center'>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<table > \r\n");
      out.write("\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width='10%' align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(pgmstatus.equalsIgnoreCase("0"))
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type='radio' checked  name='pgmstatus' value='0'><font  size='4'>طوارئ</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									else
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type='radio'name='pgmstatus' value='0'><font  size='4'>طوارئ</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td width='10%' align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									if(pgmstatus.equalsIgnoreCase("1"))
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type='radio' checked  name='pgmstatus' value='1'><font  size='4'>برامج</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									else
									{
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <input type='radio'name='pgmstatus' value='1'><font  size='4'>برامج</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t        </tr>\r\n");
      out.write("\t\t\t\t\t        </table>        \r\n");
      out.write("                \r\n");
      out.write("                </td>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <td width='25%' align='center'><input type='submit' name='subAdd' value='تطبيق' STYLE='font-size:16; color:#000000; width:5em; height:2em'></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("\t     </form>\r\n");
      out.write("            </table>\r\n");
      out.write("        \t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align='center' border='1' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#AAAAAA' width='98%'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \t      <tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write("  \t        \t<td colspan=6 align='center'><b>البرامج</b></td>\r\n");
      out.write("      \t      </tr>\r\n");
      out.write("      \t      \r\n");
      out.write("\r\n");
      out.write("<tr height='25' bgcolor=#DCDCDC>\r\n");
      out.write(" <td width='10%' align='center'><input type='submit' name='subApproveSMSSel' value='الكل' style='font-weight:bold ; width:6em ; height:2.0em' onClick='selectall(");
      out.print( count );
      out.write(")'></td>\r\n");
      out.write(" <td width='10%' align='center'><input type='submit' name='subApproveSMSSel' value='تعديل' style='font-weight:bold ; width:6em ; height:2.0em' onClick=\"thecorrectinvoke(0)\"></td>\r\n");
      out.write(" <td width='10%' align='center'><input type='submit' name='subApproveSMSSel' value='حذف' style='font-weight:bold ; width:6em ; height:2.0em' onClick=\"thecorrectinvoke(1)\"></td> \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <td colspan=2 width='65%' align='center'></td>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                          <td width='10%' align='center'>\r\n");
      out.write("                                                <table border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='100%'>\r\n");
      out.write("                                                      <tr>\r\n");
      out.write("                                                            <td align='center'><b>عدد</b></td>\r\n");
      out.write("                                                            <td align='center'><font color=#000099><b>");
      out.print( count );
      out.write("</b></font></td>\r\n");
      out.write("                                                      </tr>\r\n");
      out.write("                                                </table>\r\n");
      out.write("                                          </td>\r\n");
      out.write("                                          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <table border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#cccccc' width='98%'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           \t  <tr bgcolor=#DCDCDC height='25'>\r\n");
      out.write("         \t    <td width='5%' colspan=3 align='center'><b>&nbsp;</b></td>\r\n");
      out.write("      \t        \r\n");
      out.write("                <td width='10%' colspan=3 align='center'><font color=#000099><b>البث</b></font></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td width='10%' colspan=3 align='center'><font color=#990000><b>الاعاده</b></font></td>\r\n");
      out.write("\r\n");
      out.write("      \t        <td width='10%' colspan=2 align='center'><b>&nbsp;</b></td>\r\n");
      out.write("\r\n");
      out.write("              </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("           \t  <tr bgcolor=#DCDCDC height='25'>\r\n");
      out.write("         \t    <td width='5%' align='center'><b>&nbsp;</b></td>\r\n");
      out.write("      \t        <td width='5%' align='center'><b>مسلسل</b></td>\r\n");
      out.write("      \t        <td width='1%' align='center'><b>اسم البرنامج</b></td>\r\n");
      out.write("                <td width='10%' align='center'><font color=#000099><b>يوم</b></font></td>\r\n");
      out.write("                <td width='10%' align='center'><font color=#000099><b>بداية</b></font></td>\r\n");
      out.write("      \t        <td width='10%' align='center'><font color=#000099><b>نهاية</b></font></td>\r\n");
      out.write("                <td width='10%' align='center'><font color=#990000><b>يوم</b></font></td>\r\n");
      out.write("                <td width='10%' align='center'><font color=#990000><b>بداية</b></font></td>\r\n");
      out.write("      \t        <td width='10%' align='center'><font color=#990000><b>نهاية</b></font></td>\r\n");
      out.write("      \t        <td width='10%' align='center'><b>اسم المستخدم</b></td>\r\n");
      out.write("      \t        <td width='10%' align='center'><b>كلمة المرور</b></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=thethisfrm method=post action=\"\">\r\n");
      out.write("<INPUT type='hidden' NAME=count SIZE=6  READONLY value=\"");
      out.print( count );
      out.write("\" > \r\n");
      out.write("\r\n");
 

   rs = null;
   

   rs = con.createStatement().executeQuery("SELECT id,pgm_name,airing_weekday,airing_from,airing_to,replay_weekday,replay_from,replay_to,username,password FROM sms.nradio_pgms order by id");  
 

 int therownnum =0;  
while(rs.next())
{

 

String pgmid = rs.getString(1);
String pgmname = rs.getString(2);
String pgmairingday = rs.getString(3);
String pgmairingstart = rs.getString(4);
String pgmairingend = rs.getString(5);
String pgmreplayday = rs.getString(6);
String pgmreplaystart = rs.getString(7);
String pgmreplayend = rs.getString(8);
String theusr=rs.getString(9);
String thepass=rs.getString(10);




      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("     \r\n");
      out.write("       \t\t\t<td width='1%' align='center'>  <INPUT id=\"ischeck");
      out.print( therownnum );
      out.write("\" NAME=ischeck");
      out.print( therownnum );
      out.write(" TYPE=CHECKBOX >  </td>\r\n");
      out.write("       \r\n");
      out.write("                   <td width='1%' align='center'><b>");
      out.print(pgmid);
      out.write("</b></td>\r\n");
      out.write("                   <INPUT type='hidden' NAME=id");
      out.print( therownnum );
      out.write(" value=\"");
      out.print( pgmid );
      out.write("\" > \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='rtl' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"pgmname");
      out.print( therownnum );
      out.write("\" NAME=pgmname");
      out.print( therownnum );
      out.write(" value='");
      out.print(pgmname);
      out.write("' ></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   <td width='10%' align='center'>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                        <select name='pgmairingday");
      out.print( therownnum );
      out.write("'  style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em'  >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("ALL"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("SUNDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("MONDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("TUESDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("WEDNESDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("THURSDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("FRIDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmairingday.equalsIgnoreCase("SATURDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   </td>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"pgmairingstart");
      out.print( therownnum );
      out.write("\" NAME=pgmairingstart");
      out.print( therownnum );
      out.write(" value='");
      out.print(pgmairingstart);
      out.write("' ></td>\r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"pgmairingend");
      out.print( therownnum );
      out.write("\" NAME=pgmairingend");
      out.print( therownnum );
      out.write(" value='");
      out.print(pgmairingend);
      out.write("' ></td>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   <td width='10%' align='center'>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                        <select name='pgmreplayday");
      out.print( therownnum );
      out.write("'  style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em'  >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("NOREPLAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='NOREPLAY'>لا اعاده</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='NOREPLAY'>لا اعاده</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("ALL"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='ALL'>يوميا</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("SUNDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SUNDAY'>الاحد</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("MONDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='MONDAY'>الاثنين</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("TUESDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='TUESDAY'>الثلاثاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("WEDNESDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='WEDNESDAY'>الاربعاء</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("THURSDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='THURSDAY'>الخميس</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("FRIDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='FRIDAY'>الجمعه</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

							if(pgmreplayday.equalsIgnoreCase("SATURDAY"))
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							else
							{
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option  value='SATURDAY'>السبت</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   \t\t\t\t\r\n");
      out.write("                   </td>\r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"pgmreplaystart");
      out.print( therownnum );
      out.write("\" NAME=pgmreplaystart");
      out.print( therownnum );
      out.write(" value=");
      out.print(pgmreplaystart);
      out.write(" ></td>                          \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"pgmreplayend");
      out.print( therownnum );
      out.write("\" NAME=pgmreplayend");
      out.print( therownnum );
      out.write(" value=");
      out.print(pgmreplayend);
      out.write(" ></td>                          \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"theusr");
      out.print( therownnum );
      out.write("\" NAME=theusr");
      out.print( therownnum );
      out.write(" value=");
      out.print(theusr);
      out.write(" ></td>                          \r\n");
      out.write("                   <td width='10%' align='center'><INPUT dir='ltr' style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' id=\"thepass");
      out.print( therownnum );
      out.write("\" NAME=thepass");
      out.print( therownnum );
      out.write(" value=");
      out.print(thepass);
      out.write(" ></td>                          \r\n");
      out.write("                                      \r\n");
      out.write("                                      \r\n");
      out.write("                                      \r\n");
      out.write(" \r\n");
      out.write("           \r\n");
      out.write("                                                \r\n");
      out.write("                    \r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

therownnum = therownnum + 1;

}

rs.close();rs=null;




      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>  \r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

con.close();  
}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
