/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-12 20:42:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;
import java.util.regex.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



public String replaceWord(String inputStr,String patternStr,String replacementStr) throws Exception{return Pattern.compile(patternStr).matcher(inputStr).replaceAll(replacementStr);}
public String getReadable(String theUnicode,String thelang)
 {
   if( thelang.equalsIgnoreCase("0") ){return theUnicode;}
   
   if(theUnicode.length() < 4){return "";}
   try 
    {
     byte[] by = new byte[theUnicode.length()/2];
     for(int i=0;i<theUnicode.length()/2;i++)
     by[i] = (new Integer(Integer.parseInt(theUnicode.substring(i*2,i*2 + 2),16))).byteValue();
     String theReadable = new String(by,"UTF-16");
     return theReadable;
    }catch(Exception e){return "";}

 }







            

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


String pgmid;try{ pgmid =  session.getAttribute("pgmid").toString();}catch(Exception e){pgmid=null;}
String username;try{ username =  session.getAttribute("username").toString();}catch(Exception e){username=null;}
String password;try{password =  session.getAttribute("password").toString();}catch(Exception e){password=null;}

if( pgmid.equalsIgnoreCase("admin")  ) //admin login
{








  Connection con=null;
  InitialContext ic = new InitialContext();
  DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/TheDB");
  con  = ds.getConnection();
  ResultSet rs = null;



String theSdate =(new SimpleDateFormat("yyyy-MM-dd")).format(new java.util.Date((new java.util.Date()).getTime())).trim();
String theEdate =(new SimpleDateFormat("yyyy-MM-dd")).format(new java.util.Date( (new java.util.Date()).getTime())).trim();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
Calendar c = Calendar.getInstance();
c.setTime(sdf.parse(theEdate));
c.add(Calendar.DATE, 1);  // number of days to add
theEdate = sdf.format(c.getTime());




String stime = "00:00:01";try{stime = request.getParameter("stime").trim();}catch(Exception e){stime = "00:00:01";}
String etime = "00:00:01";try{etime = request.getParameter("etime").trim();}catch(Exception e){etime = "23:59:59";}



String fdate = "";try{fdate = request.getParameter("fdate").trim();}catch(Exception e){fdate = theSdate;}
String tdate = "";try{tdate = request.getParameter("tdate").trim();}catch(Exception e){tdate = theEdate;}




String messagetatus = "ALL";try{messagetatus = request.getParameter("messagetatus").trim();}catch(Exception e){messagetatus = "ALL";}

String searchword = "";try{searchword = request.getParameter("searchword").trim();}catch(Exception e){searchword = "";}
String searchby= "1"; try{searchby = request.getParameter("searchby").trim();}catch(Exception e){searchby = "1";}

String searchorder = "1"; try{searchorder = request.getParameter("searchorder").trim();}catch(Exception e){searchorder = "1";}



String pgms = "ALLPGMS";try{pgms =  request.getParameter("pgms").trim();    }catch(Exception e){pgms = "ALLPGMS";}



String pgmtomodify = "0";try{pgmtomodify =  request.getParameter("pgmtomodify").trim();    }catch(Exception e){pgmtomodify = "0";}





 

String operators = "ALL";try{operators = request.getParameter("operators").trim();}catch(Exception e){operators = "ALL";}



String thequery="";
thequery = " select nradio_cdrs.ID,  DATE_FORMAT(datein, '%Y-%m-%d %H:%i:%S' ) as thedatein , readtime, shortcode, msisdn, readable ,  nradio_pgms.id , nradio_pgms.pgm_name , providers.name , nradio_cdrs.Status" +
 		   " from sms.nradio_cdrs LEFT JOIN sms.nradio_pgms ON nradio_pgms.id=nradio_cdrs.pgmid LEFT JOIN sms.providers ON nradio_cdrs.provider = providers.gateway " +
		   " where (datein between '" + fdate + " " + stime + "' and '" + tdate + " " + etime + "')" ;


if(searchby.equalsIgnoreCase("1")){thequery= thequery + " and nradio_cdrs.readable like N'%" + (new String(searchword.getBytes("Cp1252"),"Cp1256")) + "%' ";}
if(searchby.equalsIgnoreCase("2")){thequery= thequery + " and nradio_cdrs.msisdn like N'%" + (new String(searchword.getBytes("Cp1252"),"Cp1256")) + "%' ";}


if(!pgms.equalsIgnoreCase("ALLPGMS"))
{

	if(pgms.equalsIgnoreCase("NOPGM"))
	{
		thequery= thequery + " and nradio_cdrs.pgmid ='0' ";
	}
	else
	{
		thequery= thequery + " and nradio_pgms.pgm_name like N'%" + (new String(pgms.getBytes("Cp1252"),"Cp1256")) + "%' ";
	}
	
}






if(!operators.equalsIgnoreCase("ALL"))
{
		thequery= thequery + " and providers.name like N'%" + (new String(operators.getBytes("Cp1252"),"Cp1256")) + "%' ";
}



if(!messagetatus.equalsIgnoreCase("ALL"))
{
		if(messagetatus.equalsIgnoreCase("0")){	thequery= thequery + "  and nradio_cdrs.Status = 0 "; }
		if(messagetatus.equalsIgnoreCase("1")){ thequery= thequery + "  and nradio_cdrs.Status = 1 "; }
	
}







if(searchorder.equalsIgnoreCase("1")){thequery= thequery + " order by nradio_cdrs.ID  asc";}
if(searchorder.equalsIgnoreCase("2")){thequery= thequery + " order by nradio_cdrs.ID  desc";}

 






//out.println(thequery);







int THECOUNT = 0 ;
   rs = null;
   rs = con.createStatement().executeQuery(thequery); 
while(rs.next())
{
THECOUNT = THECOUNT + 1;

}
rs.close();rs=null;   




//out.println(thequery);  

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html dir=rtl>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<STYLE type=text/css>\r\n");
      out.write("\r\n");
      out.write("body{font-size:62.5%;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../jquery-ui-1.10.2/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"../jquery-ui-1.10.2/jquery-1.9.1.js\"></script>\r\n");
      out.write("<script src=\"../jquery-ui-1.10.2/ui/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../jquery-ui-1.10.2/ui/jquery.timepicker.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../jquery-ui-1.10.2/ui/jquery.timepicker.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../jquery-ui-1.10.2/ui/site.js\"></script>\r\n");
      out.write("  <!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"../jquery-ui-1.10.2/ui/site.css\" /> -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<script>\r\n");
      out.write("  $(function() \r\n");
      out.write("  {\r\n");
      out.write("    $( \"#fdate\" ).datepicker({ dateFormat: 'yy-mm-dd' });\r\n");
      out.write("    $( \"#tdate\" ).datepicker({ dateFormat: 'yy-mm-dd' });\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                $(function() {\r\n");
      out.write("                    $('#stime').timepicker({ 'timeFormat': 'H:i:s'  , 'step': 1 });\r\n");
      out.write("                    $('#etime').timepicker({ 'timeFormat': 'H:i:s'  , 'step': 1 });\r\n");
      out.write("                });\r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function selectall(k)\r\n");
      out.write("{\r\n");
      out.write("\tfor( i=0; i< k; i++ )\r\n");
      out.write("\t{ \r\n");
      out.write("\t if( document.getElementById('ischeck' + i) != null )  \r\n");
      out.write("     { \r\n");
      out.write("\t   document.getElementById('ischeck' + i).checked = true; \r\n");
      out.write("\t }\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function correctinvoke(target)\r\n");
      out.write("{\r\n");
      out.write("\tif(target == 0) {document.mainform.action=\"BATCHPgmModify.jsp\";document.mainform.submit();}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>              \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



   
    int pgm_CNT=0;
    rs = con.createStatement().executeQuery("SELECT count(*) FROM sms.nradio_pgms");
    while(rs.next()){pgm_CNT=rs.getInt(1);}rs.close(); rs = null;
    
     String[] the_pgm_id = new String[pgm_CNT];
     String[] the_pgm_name = new String[pgm_CNT];
     
       int cc = 0;
       rs = con.createStatement().executeQuery("SELECT id,pgm_name FROM sms.nradio_pgms");            
       while(rs.next())
       {
         the_pgm_id[cc] = rs.getString(1);
         the_pgm_name[cc] = rs.getString(2);
         
         

     	 cc = cc + 1 ;
       }
       rs.close(); rs = null;
        



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>البحث ... National Radio</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("            <table border='1' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%' height='80'>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width='21%' align='center'><b><i><font color='#A36103' size='6'>البحث</font></i></b></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <td width='30%' align='center'>\r\n");
      out.write("                <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%'>\r\n");
      out.write("                  <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b>&nbsp;</b></font></td></tr>\r\n");
      out.write("     \t\t\t\t <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b> &nbsp;</b></font></td></tr>\r\n");
      out.write("\t\t\t\t      <tr><td width='100%' align='center'><font color='#000000' face='Arial' size='4'><b>&nbsp;</b></font></td></tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td width='19%' align='center'>\r\n");
      out.write("                \t<table border='0' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%'>\r\n");
      out.write("                \t\r\n");
      out.write("                \t<form action='AdminMainPage.jsp' method='post'>\r\n");
      out.write("               \t\t<tr>\r\n");
      out.write("                \t\t\t<td align='center'><input type='submit' name='subMain' value='القائمة الرئيسية' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td></tr>\r\n");
      out.write("                \t\t\t</form>\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t<form action='search.jsp' method='post'>\r\n");
      out.write("              \t\t<tr>\r\n");
      out.write("              \t\t\t<td align='center'><input type='submit' name='subRefresh' value='اعادة تحميل' STYLE='font-weight:bold;font-family:arial;font-size:18;color:#00f;width:12em;height:2.5em'></td>\r\n");
      out.write("              \t\t</tr>\r\n");
      out.write("                        </form> \r\n");
      out.write("                \t</table>\r\n");
      out.write("                \t\r\n");
      out.write("                </td>\r\n");
      out.write("<td bgcolor='#ffffff' width='15%' align='center'><IMG src='logo.png'></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='90%'>\r\n");
      out.write("\t\t\t  <tr height='30'>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='90%'>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<form method=\"post\">\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <td width='30%' colspan=2 align='center' >\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <table border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='100%'>\r\n");
      out.write("\t\t\t  <tr height=30>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <td  align='center'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t <table dir='ltr' border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='100%'>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t      \t\t<td colspan=2 align='center'><font color='#000000' face='Arial' size='3'>تاريخ من</font></td>\r\n");
      out.write("\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t   \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input dir='ltr' type=\"text\"  name=\"fdate\" id=\"fdate\" value='");
      out.print(fdate);
      out.write("'   style='width:7em;height:1.5em' >\r\n");
      out.write("\t\t                </td> \r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t               \t   <input dir='ltr' type=\"text\"  name=\"stime\" id=\"stime\"   value='");
      out.print(stime);
      out.write("' style='width:7em;height:1.5em' >\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t              </table>\r\n");
      out.write("            \r\n");
      out.write("              </td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    <td align='center'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t <table dir='ltr' border='0' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='100%'>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t      \t\t<td colspan=2 align='center'><font color='#000000' face='Arial' size='3'>تاريخ الي</font></td>\r\n");
      out.write("\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t   \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input dir='ltr' type=\"text\"  name=\"tdate\" id=\"tdate\" value='");
      out.print(tdate);
      out.write("'   style='width:7em;height:1.5em' >\r\n");
      out.write("\t\t                </td> \r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <td>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t               \t   <input dir='ltr' type=\"text\"  name=\"etime\" id=\"etime\"   value='");
      out.print(etime);
      out.write("' style='width:7em;height:1.5em' >\r\n");
      out.write("\t\t                </td>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t\t\t\t   </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                </table>\r\n");
      out.write("            \r\n");
      out.write("              </td>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("           </tr>\r\n");
      out.write("           </table>   \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <td width='15%' align='center'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t <table  border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#DCDCDC' width='100%'>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\r\n");
      out.write("<td width='10%' align='center'>\r\n");

if(searchby.equalsIgnoreCase("1"))
{

      out.write("\r\n");
      out.write(" <input type='radio' checked  name='searchby' value='1'><font size='3'>الرساله</font>\r\n");

}
else
{

      out.write("\r\n");
      out.write(" <input type='radio'name='searchby' value='1'><font size='3'>الرساله</font>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td width='10%' align='center'>\r\n");
      out.write("\r\n");

if(searchby.equalsIgnoreCase("2"))
{

      out.write("\r\n");
      out.write(" <input type='radio' checked  name='searchby' value='2'><font size='3'>التليفون</font>\r\n");

}
else
{

      out.write("\r\n");
      out.write(" <input type='radio'  name='searchby' value='2'><font size='3'>التليفون</font>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      \t\t\r\n");
      out.write("\t\t\t\t      </tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td colspan=2 width='20%' align='center'>\r\n");
      out.write(" <input type='text' name='searchword' value='");
      out.print((new String(searchword.getBytes("Cp1252"),"Cp1256")));
      out.write("' style='width:10em;height:1.6em'>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t      <td  width='15%' align='center'>\r\n");
      out.write("\r\n");
      out.write("<select name='pgms' style='font-weight:bold;width:9em;height:1.6em'>\r\n");
      out.write("\r\n");

  if(pgms.equalsIgnoreCase("ALLPGMS"))
{

      out.write(" \r\n");
      out.write("\t<option value='ALLPGMS' selected>الكل</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option value='ALLPGMS' >الكل</option>\r\n");

}  	        

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  if(pgms.equalsIgnoreCase("NOPGM"))
{

      out.write(" \r\n");
      out.write("\t<option value='NOPGM' selected>لا برنامج</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option value='NOPGM' >لا برنامج</option>\r\n");

}  	        

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
   rs = con.createStatement().executeQuery("select pgm_name from sms.nradio_pgms order by id");             
while(rs.next())
  {
	String temppgm=  rs.getString(1);
	
	
  if((new String(pgms.getBytes("Cp1252"),"Cp1256")).equalsIgnoreCase(temppgm))
{

      out.write(" \r\n");
      out.write("\t<option selected>");
      out.print( temppgm );
      out.write("</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option >");
      out.print( temppgm );
      out.write("</option>\r\n");

}  	        
}rs.close();rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t      <td  width='15%' align='center'>\r\n");
      out.write("\r\n");
      out.write("<select name='operators' style='font-weight:bold;width:9em;height:1.6em'>\r\n");
      out.write("\r\n");

  if(operators.equalsIgnoreCase("ALL"))
{

      out.write(" \r\n");
      out.write("\t<option value='ALL' selected>كل الشركات</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option value='ALL' >كل الشركات</option>\r\n");

}  	        

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
   rs = con.createStatement().executeQuery("select name from sms.providers order by prov_id");             
while(rs.next())
  {
	String tempop=  rs.getString(1);
  if(operators.equalsIgnoreCase(tempop))
{

      out.write(" \r\n");
      out.write("\t<option selected>");
      out.print( tempop );
      out.write("</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option >");
      out.print( tempop );
      out.write("</option>\r\n");

}  	        
}rs.close();rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                         \r\n");
      out.write("                         \r\n");
      out.write("                         \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td width='15%' align='center'>\r\n");
      out.write("\r\n");
      out.write("<select name='messagetatus' style='font-weight:bold;width:9em;height:1.6em'>\r\n");
      out.write("\r\n");
      out.write("<option value='ALL'>كل الرسائل</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(messagetatus.equalsIgnoreCase("0"))
{

      out.write("\r\n");
      out.write("<option selected value='0'>رسائل مقروءه</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("<option value='0'>رسائل مقروءه</option>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(messagetatus.equalsIgnoreCase("1"))
{

      out.write("\r\n");
      out.write("<option selected value='1'>رسائل غير مقروءه</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("<option value='1'>رسائل غير مقروءه</option>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t      <td  width='15%' align='center'>\r\n");
      out.write("\r\n");
      out.write("<select name='searchorder' style='font-weight:bold;width:6em;height:1.6em'>\r\n");
      out.write("\r\n");

  if(searchorder.equalsIgnoreCase("1"))
{

      out.write(" \r\n");
      out.write("\t<option value='1' selected>تصاعدي</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option value='1' >تصاعدي</option>\r\n");

}  	        

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  if(searchorder.equalsIgnoreCase("2"))
{

      out.write(" \r\n");
      out.write("\t<option value='2' selected>تنازلي</option>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t<option value='2' >تنازلي</option>\r\n");

}  	        

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <td width='15%' align='center'>\r\n");
      out.write("\t\t\t    \t\t<input type='submit' name='Searchbutton' value='بحث' style='font-weight:bold;width:5em;height:2em'>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t </table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t </td>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t </tr>\r\n");
      out.write("\t\t\t \r\n");
      out.write("</form>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\r\n");
      out.write("<form name=mainform method=post action=\"\" >\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <table border='1' align='center' cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#cccccc' width='98%'>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("                  <tr height=30 bgcolor=#DCDCDC>\r\n");
      out.write("                    \r\n");
      out.write("                    <td width='45%' align='center'>\r\n");
      out.write("                    \r\n");
      out.write("                    \t<table border='1' align='right' cellpadding='0' cellspacing='0' width='80%>\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t   <tr width='100%'>\r\n");
      out.write("                    \t   \r\n");
      out.write("                    \t   \t\t<td colspan=3 width='100%' align='center'> تحويل برامج </td> \r\n");
      out.write("                    \t   </tr>\r\n");
      out.write("                    \t   \r\n");
      out.write("                    \t   <tr width='100%'>\r\n");
      out.write("                    \t   \r\n");
      out.write("                    \t   \t\t\r\n");
      out.write("                    \t   \t\t\r\n");
      out.write("\t                    \t   \t<td width='25%' align='center'>\r\n");
      out.write("\t                    \t   \t\t<input type='button' value='الكل' style='font-weight:bold ; width:5em ; height:2em' onClick=\"selectall(");
      out.print( THECOUNT );
      out.write(")\"></td>\t\t\r\n");
      out.write("                    \t   \t\r\n");
      out.write("                    \t   \t\t<td width='25%' align='center'>\r\n");
      out.write("                    \t   \t\t\t<select name='pgmtomodify' style='font-weight:bold;width:9em;height:1.8em' >\r\n");
      out.write("                    \t   \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t <option value=0 >لا برنامج</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 
										for (int l =0  ; l < the_pgm_id.length ; l ++)
										{
										  if (the_pgm_id[l].equalsIgnoreCase(pgmtomodify)) 
										  {
										  
										
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t        <option value='");
      out.print( the_pgm_id[l] );
      out.write("' selected>");
      out.print( the_pgm_name[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										  }
										  else
										  {
										
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    \t        <option value='");
      out.print( the_pgm_id[l] );
      out.write('\'');
      out.write('>');
      out.print( the_pgm_name[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										  }    	        
										}
										
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                \t</select> \r\n");
      out.write("                                </td>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                                <td width='25%' align='center'>\r\n");
      out.write("                                \t\t<input type='submit' value='تحويل' style='font-weight:bold ; color:#000000; width:7em ; height:2em' onClick=\"correctinvoke(0)\">\r\n");
      out.write("                               \t</td>\r\n");
      out.write("                                \t\r\n");
      out.write("                    \t   \t\t    \r\n");
      out.write("                    \t   \r\n");
      out.write("                    \t   </tr>\r\n");
      out.write("                    \t\r\n");
      out.write("                    \t</table>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \t\t\r\n");
      out.write("                    \t\t\r\n");
      out.write("                    \t\t\r\n");
      out.write("                    </td>    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                     \r\n");
      out.write(" \t\t\t        <td width='45%' align='center'><b>&nbsp;</b></td>     \r\n");
      out.write(" \t\t\t        <td width='10%' align='center'><b>العدد</b>&nbsp;&nbsp;&nbsp;<font color=#000099><b>");
      out.print( THECOUNT );
      out.write("</b></font></td>               \r\n");
      out.write(" \t\t\t        \r\n");
      out.write("                  </tr>\r\n");
      out.write("             </table>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\r\n");

int cntr =0 ;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<INPUT style=\"display: none;\" NAME=count value=\"");
      out.print( THECOUNT );
      out.write("\" > \r\n");
      out.write("\r\n");
      out.write("\t\t\t \r\n");
      out.write("      \t\t\t\t\t<table border='1' align='center' cellpadding='0' cellspacing='1' style='border-collapse: collapse' bordercolor='#cccccc' width='100%'>\r\n");
      out.write("      \t\t\t\t\t  <tr bgcolor=#DCDCDC>\r\n");
      out.write("      \t\t\t\t\t  \t<td width='1%' align='center'>&nbsp;</td> \r\n");
      out.write("      \t\t\t\t\t    <td width='40%' rowspan=2 align='center'><b>نص الرساله</b></td>\r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>رقم تليفون</b></td>\r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>الرقم المختصر</b></td>\r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>برنامج</b></td>      \t\t\t\t\t          \t\t\t\t\t    \r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>مصدر</b></td>      \t\t\t\t\t    \r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>وقت الدخول</b></td>\r\n");
      out.write("      \t\t\t\t\t    <td width='10%' rowspan=2 align='center'><b>وقت القراءه</b></td>      \t\t\t\t\t    \r\n");
      out.write("  \t\t\t\t\t    \r\n");
      out.write("      \t\t\t\t\t  </tr>\r\n");
      out.write("\r\n");
      out.write("      \t\t\t\t\t  <tr bgcolor=#DCDCDC>\r\n");
      out.write("   \t\t\t\t\t          \t\t\t\t\t          \t\t\t\t\t          \t\t\t\t\t    \r\n");
      out.write("      \t\t\t\t\t  </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


   rs = null;
   rs = con.createStatement().executeQuery(thequery);  
while(rs.next())
{
int theid = rs.getInt(1);
String thedatein = rs.getString(2);
String thereadtime = rs.getString(3);
String theshortcode = rs.getString(4);
String themsisdn = rs.getString(5);
String themsg = rs.getString(6);
String theprogramid = rs.getString(7);
String theprogramname = rs.getString(8);
String theoperator = rs.getString(9);
String thestatus = rs.getString(10);

      
   





      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if(theid%2 ==0)
{

      out.write("\r\n");
      out.write("          <tr bgcolor=#fDfDfD height='25'>\r\n");

}
else
{

      out.write("\r\n");
      out.write("          <tr bgcolor=#f5f5f5 height='25'>\r\n");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t\t<INPUT style=\"display: none;\" NAME=id");
      out.print( cntr );
      out.write(" value=\"");
      out.print( theid );
      out.write("\" > \r\n");
      out.write("\r\n");
      out.write("\t\t\t<td width='1%'  align='center'>  <INPUT id=\"ischeck");
      out.print( cntr );
      out.write("\" NAME=ischeck");
      out.print( cntr );
      out.write(" TYPE=CHECKBOX >  </td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<td width='40%' align='center'>");
      out.print(themsg);
      out.write("</td>\r\n");
      out.write("    \t    <td width='10%' align='center'><font color=#000000 size=3 dir='ltr' >");
      out.print( themsisdn );
      out.write("</font></td>\r\n");
      out.write("\t  \t    <td width='10%' align='center'><font color=#000000 size=3 dir='ltr' >");
      out.print( theshortcode );
      out.write("</font></td>\r\n");
      out.write("\t  \t    \r\n");
      out.write("\t  \t    <td width='10%' align='center'><font color=#000000 size=3 dir='ltr' >");
      out.print( theprogramname );
      out.write("</font></td>\r\n");
      out.write("\t  \t    <td width='10%' align='center'><font color=#000000 size=3 dir='ltr' >");
      out.print( theoperator );
      out.write("</font></td>\r\n");
      out.write("\t  \t    \r\n");
      out.write("      \t    <td width='10%' align='center'><font color=#000000 size=2 dir='ltr' >");
      out.print( thedatein );
      out.write("</font></td>\r\n");
      out.write("      \t    <td width='10%' align='center'><font color=#000000 size=2 dir='ltr' >");
      out.print( thereadtime );
      out.write("</font></td>      \t\t\t\t\t    \r\n");
      out.write("\r\n");
      out.write("      \t\t\t\t\t    \r\n");
      out.write("\r\n");
      out.write("      \t\t\t\t\t    \r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");

cntr = cntr +1 ;

}

rs.close();rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


con.close();

}

else
{

	session.invalidate();
	response.sendRedirect("login.jsp");

}



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
