/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-09-12 19:42:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;
import java.util.regex.*;

public final class thebatchprogramsmodify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


  Connection con=null;
 InitialContext ic = new InitialContext();
  DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/TheDB");
  con  = ds.getConnection();
 

 int count = 0 ;


 count = Integer.parseInt(request.getParameter("count"));
 
   String[] ischeck = new String[count];
   String[] id = new String[count];
   
   String[] pgmname = new String[count];
     
   String[] pgmairingday = new String[count];
   String[] pgmairingstart = new String[count];
   String[] pgmairingend = new String[count];
   
   String[] pgmreplayday =   new String[count];
   String[] pgmreplaystart =   new String[count];
   String[] pgmreplayend=   new String[count];

   String[] theusr  =   new String[count];
   String[] thepass =   new String[count];

   

for (int i=0; i < count;i++)
{
   ischeck[i] = request.getParameter("ischeck"+ Integer.toString(i) );
   id[i] = request.getParameter("id"+ Integer.toString(i));
   
   pgmname[i] = request.getParameter("pgmname"+ Integer.toString(i));
   
   pgmairingday[i] = request.getParameter("pgmairingday"+ Integer.toString(i));
   pgmairingstart[i] = request.getParameter("pgmairingstart"+ Integer.toString(i));
   pgmairingend[i] = request.getParameter("pgmairingend"+ Integer.toString(i));
   
   pgmreplayday[i] = request.getParameter("pgmreplayday"+ Integer.toString(i));
   pgmreplaystart[i] = request.getParameter("pgmreplaystart"+ Integer.toString(i));
   pgmreplayend[i] = request.getParameter("pgmreplayend"+ Integer.toString(i));
   
   theusr[i] = request.getParameter("theusr"+ Integer.toString(i));
   thepass[i] = request.getParameter("thepass"+ Integer.toString(i));
   
      
  out.println("<br><br>");
   
}
 	
 	
 
	
ResultSet rs = null; 	

for (int i =0;i< count ;i ++)
{
  if(ischeck[i] != null)
  {
      try{

    	  String query="";
          query= "update  sms.nradio_pgms set pgm_name='" + (new String(pgmname[i].getBytes("Cp1252"),"Cp1256")) + "',airing_weekday='" + pgmairingday[i] + "',airing_from='" + pgmairingstart[i] + "', airing_to='" + pgmairingend[i] + "' , replay_weekday='" + pgmreplayday[i] + "',replay_from = '" + pgmreplaystart[i] + "' , replay_to= '" + pgmreplayend[i] + "' , username = '" + (new String(theusr[i].getBytes("Cp1252"),"Cp1256")) + "' , password= '" + (new String(thepass[i].getBytes("Cp1252"),"Cp1256")) + "'  where id= " +id[i] ;
   



 //  out.println(query);
  con.createStatement().execute(query); 
     
         }catch(Exception e){}
  }

}

con.close();

     response.sendRedirect("programs.jsp");    



   		          
 

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
