/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2015-08-11 14:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import java.sql.*;
import javax.naming.*;
import javax.sql.*;
import java.net.*;

public final class smsreport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



  Connection con=null;
  InitialContext ic = new InitialContext();
  DataSource ds = (DataSource) ic.lookup("java:comp/env/jdbc/TheDB");
  con  = ds.getConnection();
  ResultSet rs = null;

/*
  int count = 0 ;
  rs = null;
  try
  {
   rs = con.createStatement().executeQuery("SELECT count(*) from mo_cdrs");             
   while(rs.next()){count = rs.getInt(1);} 
   rs.close();rs = null;
  }catch(Exception e){}
 */ 








String theSdate =(new SimpleDateFormat("yyyyMMdd")).format(new java.util.Date((new java.util.Date()).getTime())).trim();
String theEdate =(new SimpleDateFormat("yyyyMMdd")).format(new java.util.Date( (new java.util.Date()).getTime())).trim();
SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
Calendar c = Calendar.getInstance();
c.setTime(sdf.parse(theEdate));
c.add(Calendar.DATE, 1);  // number of days to add
theEdate = sdf.format(c.getTime());



String fdate = "";try{fdate = request.getParameter("fdate").trim();}catch(Exception e){fdate = theSdate;}
String tdate = "";try{tdate = request.getParameter("tdate").trim();}catch(Exception e){tdate = theEdate;}

   
String sdate_formated = fdate.substring(0,4) + "-" + fdate.substring(4,6) + "-" + fdate.substring(6,8);
String edate_formated = tdate.substring(0,4) + "-" + tdate.substring(4,6) + "-" + tdate.substring(6,8);



String query1 = "";
query1 = query1 + " SELECT providers.name as operatorname, mo_cdrs.shortcode  , sum(mo_cdrs.length) as thecount  " ;
query1 = query1 + " FROM mo_cdrs,providers where mo_cdrs.Provider = providers.gateway   ";
query1 = query1 + " and  shortcode in ('1421','+2491421','+2491653','1653','+2495006') ";
query1 = query1 + " and datein between '"+sdate_formated+"' and '"+edate_formated+"' ";

 
String query2 = "";
query2 = query2 + " SELECT sum(mo_cdrs.length) as thecount  " ;
query2 = query2 + " FROM mo_cdrs,providers where mo_cdrs.Provider = providers.gateway  " ;
query2 = query2 + " and  shortcode in ('1421','+2491421','+2491653','1653','+2495006') ";
query2 = query2 + " and datein between '"+sdate_formated+"' and '"+edate_formated+"' ";






String filteroperator = "ALL";
if( request.getParameter("filteroperator")!=null) 
{
 if( !(request.getParameter("filteroperator").trim().equalsIgnoreCase("ALL")) ) 
 { 
  filteroperator= request.getParameter("filteroperator");
  query1 = query1 + " and providers.name='" + filteroperator + "' ";
  query2 = query2 + " and providers.name='" + filteroperator + "' ";
 }
} 
   


///////////////THE operators
int theoperatorscount = 0;
String[] theoperators = null;

   try{
      rs = con.createStatement().executeQuery("select distinct name from providers order by name asc");            
      while(rs.next())
      {
     	 theoperatorscount = theoperatorscount + 1;
      }
       rs.close(); rs = null;

   rs = null;
   rs = con.createStatement().executeQuery("select distinct name from providers order by name asc");

 theoperators = new String[theoperatorscount];
   
   
   int theCounterrr1 = 0;
   while(rs.next())
    {
     try{
         theoperators[theCounterrr1] = rs.getString(1).trim();
        }catch(Exception ex){theoperators[theCounterrr1]="";}
        

     theCounterrr1 = theCounterrr1 + 1 ;
   }
   rs.close(); 
   rs = null;
   
      }catch(Exception e){out.println(e);return;}

/// ------------------





















String filtershortcode = "ALL";
if( request.getParameter("filtershortcode")!=null) 
{
 if( !(request.getParameter("filtershortcode").trim().equalsIgnoreCase("ALL")) ) 
 { 
  filtershortcode= request.getParameter("filtershortcode");
  query1 = query1 + " and shortcode='" + filtershortcode + "' ";
  query2 = query2 + " and shortcode='" + filtershortcode + "' ";
 }
} 
   


///////////////THE shortcodes
int theshortcodescount = 0;
String[] theshortcodes = null;

   try{
      rs = con.createStatement().executeQuery("SELECT shortcode,count(*) as thecnt FROM sms.mo_cdrs where shortcode in ('1421','+2491421','+2491653','1653')   group by shortcode  order by shortcode asc");            
      while(rs.next())
      {
     	 theshortcodescount = theshortcodescount + 1;
      }
       rs.close(); rs = null;

   rs = null;
   rs = con.createStatement().executeQuery("SELECT shortcode,count(*) as thecnt FROM sms.mo_cdrs where shortcode in ('1421','+2491421','+2491653','1653')   group by shortcode  order by shortcode asc");

 theshortcodes = new String[theshortcodescount];
   
   
   int theCounterrr1 = 0;
   while(rs.next())
    {
     try{
         theshortcodes[theCounterrr1] = rs.getString(1).trim();
        }catch(Exception ex){theshortcodes[theCounterrr1]="";}
        

     theCounterrr1 = theCounterrr1 + 1 ;
   }
   rs.close(); 
   rs = null;
   
      }catch(Exception e){out.println(e);return;}

/// ------------------







query1 = query1 + " group by providers.name, mo_cdrs.shortcode order by providers.name asc, mo_cdrs.shortcode asc  ";
















             

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html dir=ltr>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"ico/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"datepicker.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<STYLE type=text/css>BODY {MARGIN: 0px; FONT: 14pt arial, geneva, lucida, \"lucida grande\", arial, helvetica, sans-serif; COLOR: #000000;background-color: #FFFFFF; }</style>\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"en-us\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1256\">\r\n");
      out.write("<title>SMS Report</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<form action='smsreport.jsp' method='post'>\r\n");
      out.write("<input type='hidden' name='uid' value='41'>\r\n");
      out.write("<table border='0' bgcolor=#FFFFFF cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='100%' height='80'>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width='21%' align='center'></td>\r\n");
      out.write("    <td width='35%' align='center'>\r\n");
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td width='19%' align='center'>\r\n");
      out.write("\r\n");
      out.write("    </td>\r\n");
      out.write("    <td bgcolor='#FFFFFF' width='15%' align='center'><IMG src='logo.png'></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border='0' align='center' bgcolor=#FFFFFF cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#A36103' width='90%' height='40' >\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td align='center'><font color=#000000 size='5'0>General SMS Report for Sudan</td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("            <table border='1' align='center' bgcolor=#F9DEA9 cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='80%'>\r\n");
      out.write("                 <form action='smscount.jsp' method='post'>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                              <table border='0' align='center' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='100%'>\r\n");
      out.write("                                          <td width='5%' align='center'><b><input type=button value=\"From\" onclick=\"displayDatePicker('fdate', this);\"></td>\r\n");
      out.write("                                          <td width='20%' align='center'><input  style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' type=\"text\" readonly name=\"fdate\" id=\"idate\" value='");
      out.print(fdate);
      out.write("' ></td>\r\n");
      out.write("                                          <td width='10%' align='center'>&nbsp;</td>\r\n");
      out.write("                                          <td width='5%' align='center'><b><input type=button value=\"To\" onclick=\"displayDatePicker('tdate', this);\"></b></td>\r\n");
      out.write("                                          <td width='20%' align='center'><input style='font-size:12pt;color:#000000;font-weight:bold;width:8em;height:1.7em' type=\"text\"  readonly name=\"tdate\" id=\"idate\" value='");
      out.print(tdate);
      out.write("'></td>\r\n");
      out.write("                                          <td width='10%' align='center'>&nbsp;</td>\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='5%' align='center'>Operator</td>\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='20%' align='center'>\r\n");
      out.write("                                          \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name='filteroperator' style='font-size:12pt;color:#000099;font-weight:bold;width:8em;height:1.7em' >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <option>ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 
											for (int l =0  ; l < theoperators.length ; l ++)
											{
											  if (theoperators[l].equalsIgnoreCase(filteroperator)) 
											  {
											  
											
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    \t        <option selected>");
      out.print( theoperators[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											  }
											  else
											  {
											
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    \t        <option>");
      out.print( theoperators[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											  }    	        
											}
											
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>                                          \t\r\n");
      out.write("                                          \t\r\n");
      out.write("                                          \t\r\n");
      out.write("                                          \t</td>\r\n");
      out.write("                                          \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                          <td width='10%' align='center'>&nbsp;</td>\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='5%' align='center'>ShortCode</td>\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='20%' align='center'>\r\n");
      out.write("                                          \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name='filtershortcode' style='font-size:12pt;color:#000099;font-weight:bold;width:8em;height:1.7em' >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t <option>ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
 
											for (int l =0  ; l < theshortcodes.length ; l ++)
											{
											  if (theshortcodes[l].equalsIgnoreCase(filtershortcode)) 
											  {
											  
											
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    \t        <option selected>");
      out.print( theshortcodes[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											  }
											  else
											  {
											
      out.write("       \t        \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    \t        <option>");
      out.print( theshortcodes[l] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											  }    	        
											}
											
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>                                          \t\r\n");
      out.write("                                          \t\r\n");
      out.write("                                          \t\r\n");
      out.write("                                          \t</td>\r\n");
      out.write("\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='20%' align='center'>&nbsp;</td>\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <td width='10%' align='right'><input type='submit' name='subReport' value='Get Report' STYLE='font-weight:bold ; color:#000000; width:8em; height:2.2em'></td>\r\n");
      out.write("                              </table>\r\n");
      out.write("                                  <td width='10%' align='right'><a href=\"/ivrfit/miniutesreport.jsp\" class=\"btn btn-info btn-md\" role=\"button\">IVR Report</a></td>\r\n");
      out.write("                                  <td width='10%' align='right'><a href=\"/ivrfit/login.jsp\" class=\"btn btn-danger\" role=\"button\">Sign Out</a></td>\r\n");
      out.write("                        </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </form>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("            <table border='1' align='center' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='75%'>\r\n");
      out.write("                  <tr height=30>\r\n");
      out.write("                        <td width='15%' align='center'><font size='4'>Operator</font></td>\r\n");
      out.write("                        <td width='15%' align='center'><font size='4'>ShortCode</font></td>\r\n");
      out.write("                        <td width='15%' align='center'><font size='4'>SMS Count</font></td>\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("\r\n");


   rs = null;
   rs = con.createStatement().executeQuery(query1);  
while(rs.next())
{
String operator =rs.getString(1);
String sc =rs.getString(2);
String smscount = rs.getString(3);



      out.write("\r\n");
      out.write("\t\t\t  <tr height=30 bgcolor=#ffffff>\r\n");
      out.write("\t\t\t\t<td width='15%' align='center'><font size='3'>");
      out.print(operator);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t<td width='15%' align='center'><font size='3'>");
      out.print(sc);
      out.write("</font></td>\r\n");
      out.write("\t\t\t\t<td width='15%' align='center'><font size='3'>");
      out.print(smscount);
      out.write("</font></td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t  </tr>\r\n");

}
rs.close();rs = null;


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table border='1' align='center' bgcolor=#DCDCDC cellpadding='0' cellspacing='0' style='border-collapse: collapse' bordercolor='#111111' width='75%'>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");

	
			   rs = null;
			   rs = con.createStatement().executeQuery(query2);  
			while(rs.next())
			{
				String thecallstotal =rs.getString(1);
				String theminutestotal ="";
	
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  <tr height=30 bgcolor=#DCDCDC>\r\n");
      out.write("\t\t\t\t\t\t\t<td width='30%' align='center'><font size='4'>&nbsp;</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width='15%' align='center'><font size='4'>");
      out.print(thecallstotal);
      out.write("</font></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t");

			}
			rs.close();rs = null;
			
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");



con.close();


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
